steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMAGE', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 
          '$_IMAGE']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'palm2-run-demo', '--port', '7860', '--image', '$_IMAGE', '--region', '$LOCATION',  '--platform','managed','--project','$PROJECT_ID','--allow-unauthenticated']
substitutions:
  _IMAGE_NAME: palm2-run-image # default value
  _IMAGE_VERSION: v1 # default value
  _IMAGE_REPO: cloud-run-source-deploy
  _IMAGE: ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_IMAGE_REPO}/${_IMAGE_NAME}:${_IMAGE_VERSION}
options:
    dynamicSubstitutions: true
